### ISSUE TITLE
可能存在内存泄漏问题？

### ISSUE THREAD

**Issue by Macesuted** [optimize-2/extend-luogu#30]
近期我发现我的 chrome 多次出现内存占用高的情况，经检查占用内存高的页面均为 Luogu 页面，并且活动窗口内存占用保持快速增加（大约 80MB/s）。

![image](https://user-images.githubusercontent.com/57275149/123034480-24698500-d41c-11eb-9238-a4bd054af712.png)

关闭 exlg 插件后页面内存占用正常，不存在此问题。

**Comment by Minstdfx** [comment]
现在版本的钩子应该没什么大问题了
